version: '3.1'

services:

  app:
    image: contextcloud/diary-be
    ports:
      - "8080:8080"

  diary-db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: diary_admin
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: diary
